name: Ansible Galaxy

on:
  push:
    branches:
      - main
    paths:
      - 'galaxy.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy the collection
      uses: artis3n/ansible_galaxy_collection@v2
      with:
        api_key: ${{ secrets.GALAXY_API_KEY }}
